// <auto-generated />
using MVC_ASP.NET_ForumApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_ASP.NET_ForumApp.Migrations
{
    [DbContext(typeof(ForumAppDbContext))]
    [Migration("20230609100344_New")]
    partial class New
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_ASP.NET_ForumApp.Data.Models.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "9fb50736-8c5e-43b4-bdfd-1473b00630c4",
                            Content = "Some content",
                            Title = "Test"
                        },
                        new
                        {
                            Id = "6245ad44-3bef-47e5-866c-b3e12d240671",
                            Content = "Some content",
                            Title = "Test"
                        },
                        new
                        {
                            Id = "075f25e3-5ff4-49a9-b097-7364f2cbed4f",
                            Content = "Some content",
                            Title = "Test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
