CREATE DATABASE NationalTouristSitesOfBulgaria
GO
USE NationalTouristSitesOfBulgaria
GO

CREATE TABLE Categories
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Locations
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Municipality VARCHAR(50) NULL,
	Province VARCHAR(50) NULL
)

CREATE TABLE Sites
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(100) NOT NULL,
	LocationId INT FOREIGN KEY REFERENCES Locations(Id) NOT NULL,
	CategoryId INT FOREIGN KEY REFERENCES Categories(Id) NOT NULL,
	Establishment VARCHAR(15) NULL
)

CREATE TABLE Tourists
(
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Age INT CHECK(Age >=0 AND Age <=120) NOT NULL,
	PhoneNumber VARCHAR(20) NOT NULL,
	Nationality VARCHAR(30) NOT NULL,
	Reward VARCHAR(20) NULL
)

CREATE TABLE SitesTourists
(
	TouristId INT FOREIGN KEY REFERENCES Tourists(Id) NOT NULL,
	SiteId INT FOREIGN KEY REFERENCES Sites(Id) NOT NULL
	PRIMARY KEY(TouristId,SiteId)
)

CREATE TABLE BonusPrizes
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	Name VARCHAR(50) NOT NULL

)

CREATE TABLE TouristsBonusPrizes
(
	TouristId INT FOREIGN KEY REFERENCES Tourists(Id) NOT NULL,
	BonusPrizeId INT FOREIGN KEY REFERENCES BonusPrizes(Id) NOT NULL
	PRIMARY KEY(TouristId,BonusPrizeId)
)